baseURL: /
languageCode: en
defaultContentLanguage: en
hasCJKLanguage: yes
title: 「雜」zaap
copyright: Xiaohao Yang & Qingru Yang
theme: hugo-theme-itheme
paginate: 5
params:
  blogroll:
    - name: qingruYANG
      url: https://qingruya.myportfolio.com/
    - name: xiaohaoYANG
      url: https://xiaohaoyportfolio.com/
  defaultCover: https://raw.githubusercontent.com/billbillbilly/zaap/28ef209a3fcb2f092e3abc0d7c5e29f1e5199bbe/public/images/zaap-03.svg
  email: zaap[at]outlook[dot]com
  socialMedia:
    - name: Github
      url: https://github.com/
    - name: Twitter
      url: https://twitter.com/
publishdir: public
markup:
  goldmark:
    renderer:
      unsafe: true
