baseURL: /
languageCode: en
defaultContentLanguage: en
hasCJKLanguage: yes
title: 「雜」zaap_Studio
copyright: Xiaohao Yang & Qingru Yang
theme: hugo-theme-itheme
paginate: 5
params:
  blogroll:
    - name: qingruYANG
      url: https://qingruya.myportfolio.com/
    - name: xiaohaoYANG
      url: https://xiaohaoyportfolio.com/
  defaultCover: https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg
  email: zaap[at]outlook[dot]com
  socialMedia:
    - name: Github
      url: https://github.com/floyd-li
    - name: Twitter
      url: https://twitter.com/some-one

markup:
  goldmark:
    renderer:
      unsafe: true
